# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [179]:
print(np.__version__)
np.show_config()

1.13.3
atlas_threads_info:
  NOT AVAILABLE
lapack_opt_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
blas_src_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
lapack_src_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
lapack_info:
  NOT AVAILABLE
blas_opt_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
blas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [9]:
z = np.zeros((10,10))
z.size * z.itemsize

800

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [15]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
z = np.zeros(10)
z[4] = 1
print(z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [19]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [21]:
np.arange(50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [23]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [28]:
#np.arange(6)[np.array([1,2,0,0,4,0]) != 0]
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [29]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [35]:
np.random.random((3,3,3))

array([[[ 0.60562872,  0.33182956,  0.90386039],
        [ 0.60261287,  0.61949774,  0.66501556],
        [ 0.20707837,  0.2449415 ,  0.91269995]],

       [[ 0.17609209,  0.21549639,  0.73731258],
        [ 0.60348437,  0.64806749,  0.75023101],
        [ 0.46047311,  0.26062129,  0.11298052]],

       [[ 0.30762431,  0.04707665,  0.41852697],
        [ 0.16042962,  0.76901908,  0.56088735],
        [ 0.25009071,  0.78476089,  0.10755596]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [39]:
z = np.random.random((10,10))
np.min(z),np.max(z),z.min(),z.max()

(0.01364484858957582,
 0.99191680914858849,
 0.01364484858957582,
 0.99191680914858849)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [42]:
z = np.random.random(30)
np.average(z), z.mean()

(0.44091309200041456, 0.44091309200041456)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [45]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [60]:
z = np.ones((10,10))
#z = np.vstack([np.zeros(10), z, np.zeros(10)])
#z = np.hstack([np.zeros((12,1)),z,np.zeros((12,1))])
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [64]:
[0 * np.nan, np.nan == np.nan, np.inf > np.nan, np.nan - np.nan, 0.3 == 3 * 0.1]

[nan, False, False, nan, False]

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [67]:
np.diag(1 + np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [71]:
z = np.zeros((8,8), dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [75]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [82]:
np.tile(np.flip(np.eye(2,dtype=int),axis=1),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [84]:
z = np.random.random((5,5))
ma,mi = z.max(), z.min()
z = (z - mi) / (ma -mi)
print(z)

[[ 0.4660738   0.76342685  0.1019072   1.          0.44816835]
 [ 0.91843972  0.94475736  0.3217742   0.03348244  0.14226226]
 [ 0.18360132  0.19664574  0.40038936  0.06062254  0.26988959]
 [ 0.97133501  0.70522256  0.37004477  0.98930236  0.03257758]
 [ 0.59790029  0.06021237  0.          0.91138909  0.89790737]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [87]:
color = np.dtype([("r", np.ubyte,1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte,1  )])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [91]:
np.random.random((5,3)) @  np.random.random((3,2))

array([[ 0.6563708 ,  0.46118976],
       [ 0.88947041,  0.71514347],
       [ 0.6833494 ,  0.51784017],
       [ 0.92950365,  0.89079711],
       [ 0.99049791,  0.88704488]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [98]:
z = np.arange(11)
z[(3 <=z) &  (z < 9)] *= -1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [99]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [102]:
Z**Z
#2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [109]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

array([ nan])

#### 29. How to round away from zero a float array ? (★☆☆)

In [111]:
z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[-7.  8. -8.  8.  9.  5. -4. -9. -9. -9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [112]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print(np.intersect1d(z1,z2))

[0 1 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [114]:
defaults = np.seterr(all='ignore')
z = np.ones(1) / 0
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [115]:
np.sqrt(-1) == np.emath.sqrt(-1)

/opt/venvs/dev/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [117]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [118]:
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [119]:
a = np.ones(3) * 1
b = np.ones(3) * 2
c = np.ones(3) * 3
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [120]:
z = np.random.uniform(0,10,10)
print(z-z%1)
print(np.floor(z))
print(np.ceil(z) -1)
print(z.astype(int))
print(np.trunc(z))

[ 2.  8.  1.  0.  3.  6.  4.  2.  4.  6.]
[ 2.  8.  1.  0.  3.  6.  4.  2.  4.  6.]
[ 2.  8.  1.  0.  3.  6.  4.  2.  4.  6.]
[2 8 1 0 3 6 4 2 4 6]
[ 2.  8.  1.  0.  3.  6.  4.  2.  4.  6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [122]:
np.arange(25).reshape((5,5)) % 5

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [125]:
def generate():
    for x in range(10):
        yield x
        
z = np.fromiter(generate(), dtype=float, count=-1)
print(z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [128]:
np.linspace(0,1,11,endpoint=False)[1:]

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [129]:
z = np.random.random(10)
z.sort()
print(z) 

[ 0.08245217  0.14064672  0.21137181  0.24827862  0.43780779  0.50822909
  0.5393029   0.7289325   0.92951813  0.96448423]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [133]:
z = np.arange(10)
np.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [136]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

equal = np.allclose(a,b)
print(equal)

equal = np.array_equal(a,b)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [137]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [138]:
z = np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[ 0.67281751  1.31337084  0.2687663   0.93568035  0.57189027  1.11828791
  0.32769787  0.72265152  1.003915    0.76991092]
[ 0.65333621  0.83997032  1.23394162  0.21861394  0.4032137   0.76920371
  0.59418019  0.84232511  0.3139638   0.98008278]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [144]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[ 0.69448394  0.02383496  0.89461502  0.41937519  0.84286642  0.51941468
  0.06635655  0.56742021  0.3463204   0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [150]:
z = np.zeros((5,5), [('x',float),('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(z)

[[( 0.  ,  0.  ) ( 0.25,  0.  ) ( 0.5 ,  0.  ) ( 0.75,  0.  )
  ( 1.  ,  0.  )]
 [( 0.  ,  0.25) ( 0.25,  0.25) ( 0.5 ,  0.25) ( 0.75,  0.25)
  ( 1.  ,  0.25)]
 [( 0.  ,  0.5 ) ( 0.25,  0.5 ) ( 0.5 ,  0.5 ) ( 0.75,  0.5 )
  ( 1.  ,  0.5 )]
 [( 0.  ,  0.75) ( 0.25,  0.75) ( 0.5 ,  0.75) ( 0.75,  0.75)
  ( 1.  ,  0.75)]
 [( 0.  ,  1.  ) ( 0.25,  1.  ) ( 0.5 ,  1.  ) ( 0.75,  1.  )
  ( 1.  ,  1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [160]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.16363712


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [161]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.40282e+38
3.40282e+38
1.19209e-07
-1.79769313486e+308
1.79769313486e+308
2.22044604925e-16


#### 49. How to print all the values of an array? (★★☆)

In [163]:
np.set_printoptions(threshold=np.nan)
z = np.zeros((16,16))
print(z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [165]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print(z[index])

15


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [169]:
z = np.zeros(10, [('position',[('x',float, 1), ('y', float, 1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
print(z)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [170]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[ 0.          0.25537953  0.21141497  0.49587745  0.57851456  0.43313027
   0.40281888  0.60933157  0.5251087   0.20124151]
 [ 0.25537953  0.          0.04463477  0.31300976  0.79229668  0.65609125
   0.27684454  0.80405801  0.72951378  0.14067598]
 [ 0.21141497  0.04463477  0.          0.33239503  0.75014681  0.61290482
   0.2932534   0.76382782  0.68811144  0.12508978]
 [ 0.49587745  0.31300976  0.33239503  0.          0.8691994   0.76514502
   0.55538411  0.84817803  0.7980338   0.45293519]
 [ 0.57851456  0.79229668  0.75014681  0.8691994   0.          0.14767188
   0.98093971  0.08850404  0.07166558  0.77886294]
 [ 0.43313027  0.65609125  0.61290482  0.76514502  0.14767188  0.
   0.83470237  0.20175269  0.1131969   0.63414329]
 [ 0.40281888  0.27684454  0.2932534   0.55538411  0.98093971  0.83470237
   0.          1.01133002  0.92783076  0.20709589]
 [ 0.60933157  0.80405801  0.76382782  0.84817803  0.08850404  0.20175269
   1.01133002  0.          0.08942102  0.80588448]
 [ 0.525

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
z = np.arange(10, dtype=np.int32)
z = z.astype(np.float32, copy=False)
print(z)

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
z = np.genfromtxt(s, delimiter=',', dtype=np.int)
print(z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
z = np.arange(9).reshape(3.3)

for index, value in np.ndenumerate(z):
    print(index, value)
for index in np.ndindex(z.shape):
    print(index, z[index])

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(x*x + y * y)
signam, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma ** 2 )))
print(G)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
z = np.zeros((n,n))
np.put(z,np.random.choise(range(n*n), p, replace=False),1)
print(z)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
x = np.random.rand(5,10)
y = x - x.mean(axis=1,keepdims=True)
print(y)

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
z = np.random.randing(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
z = np.random.randint(0,3,(3,10))
print((~z.any(axis=0)).any())

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
z = np.random.uniform(0,1,10)
zz = 0.5
m = z.flat[np.abs(z-zz).argmin()]
print(m)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [6]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it:
    z[...] = x + y
print(it.operands[2])

0 0 0
0 1 1
0 2 2
1 0 1
1 1 2
1 2 3
2 0 2
2 1 3
2 2 4
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [7]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [13]:
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[ 3.  2.  4.  2.  2.  5.  6.  2.  2.  2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [16]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [17]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [18]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)

[[49 48 44 56]
 [43 54 48 57]
 [32 52 66 58]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [20]:
d = np.random.uniform(0,1,100)
s = np.random.randint(0,10,100)
d_sums = np.bincount(s,weights=d)
d_counts = np.bincount(s)
d_means = d_sums / d_counts
print(d_means)

[ 0.70931612  0.49341759  0.47751128  0.43447849  0.50571195  0.46992388
  0.54575929  0.47954144  0.41006736  0.56096548]


#### 69. How to get the diagonal of a dot product? (★★★)

In [24]:
a = np.random.uniform(0,1,(5,5))
b = np.random.uniform(0,1,(5,5))
np.diag(a @ b)

array([ 0.45696101,  1.14169425,  1.50512912,  1.57150343,  1.39571484])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [25]:
z = np.array([1,2,3,4,5])
nz = 3
z0 = np.zeros(len(z) + (len(z) - 1) * nz)
z0[::nz+1] = z
print(z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [38]:
a = np.ones((5,5,3))
b = np.random.randint(0,10,(5,5))
a * b[... ,None]

array([[[ 8.,  8.,  8.],
        [ 5.,  5.,  5.],
        [ 5.,  5.,  5.],
        [ 3.,  3.,  3.],
        [ 8.,  8.,  8.]],

       [[ 9.,  9.,  9.],
        [ 9.,  9.,  9.],
        [ 8.,  8.,  8.],
        [ 6.,  6.,  6.],
        [ 3.,  3.,  3.]],

       [[ 6.,  6.,  6.],
        [ 1.,  1.,  1.],
        [ 6.,  6.,  6.],
        [ 9.,  9.,  9.],
        [ 2.,  2.,  2.]],

       [[ 5.,  5.,  5.],
        [ 2.,  2.,  2.],
        [ 0.,  0.,  0.],
        [ 1.,  1.,  1.],
        [ 8.,  8.,  8.]],

       [[ 9.,  9.,  9.],
        [ 6.,  6.,  6.],
        [ 0.,  0.,  0.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.]]])

#### 72. How to swap two rows of an array? (★★★)

In [43]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [49]:
c = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(c)),c)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [53]:
def moving_average(a,n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:]  / n
z = np.arange(20)
print(moving_average(z,n=3))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [67]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

z = rolling(np.arange(10), 3)
print(z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [61]:
z0 = np.random.randint(0,1,10)
np.logical_not(z0,out=z0)

z1 = np.random.uniform(-1,1,100)
np.negative(z1,out=z1)

array([ 0.51349421,  0.288474  , -0.91083203,  0.39618765, -0.77400811,
       -0.09610375, -0.39551823,  0.97567094,  0.80123783,  0.36742181,
        0.89060809,  0.55351659, -0.46813128,  0.64754451,  0.55107152,
       -0.70818664,  0.82799616, -0.27515771, -0.16063408,  0.47331367,
        0.21665755,  0.61048023, -0.17741555, -0.56738612, -0.13569484,
        0.6925269 ,  0.62897137, -0.97898278, -0.54230889, -0.31872366,
       -0.46349598, -0.90001603,  0.39780858, -0.15603605, -0.24579435,
        0.49026754,  0.80407245,  0.31802816, -0.86413912,  0.42494334,
       -0.41092099, -0.30466   ,  0.42271091,  0.54812982, -0.72167675,
       -0.48587004,  0.38055194, -0.32971595,  0.25731997, -0.65707844,
       -0.72320406, -0.18776868, -0.70104222, -0.80089315,  0.83679425,
        0.44684294,  0.21901582, -0.47193555, -0.8270517 , -0.99907016,
       -0.22309521, -0.37346599, -0.9622163 , -0.59852706,  0.7311952 ,
       -0.18595855, -0.94900277, -0.91963281, -0.51926158,  0.74

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [69]:
z = np.arange(1, 15)
r = stride_tricks.as_strided(z, (11,4),(z.itemsize,z.itemsize))
print(r)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [70]:
z = np.random.uniform(0,1,(10,10))
u, s, v = np.linalg.svd(z)
rank = np.sum(s > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [72]:
z = np.random.randint(0,10,50)
print(np.bincount(z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [77]:
z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (z.shape[0] -3)
j = 1 + (z.shape[1]-3)
c = stride_tricks.as_strided(z, shape=(i,j,n,n),strides = z.strides + z.strides)
print(c)

[[[[0 2 4]
   [1 3 0]
   [3 4 1]]

  [[2 4 2]
   [3 0 1]
   [4 1 0]]

  [[4 2 4]
   [0 1 4]
   [1 0 1]]

  [[2 4 4]
   [1 4 1]
   [0 1 2]]

  [[4 4 1]
   [4 1 1]
   [1 2 3]]

  [[4 1 0]
   [1 1 0]
   [2 3 1]]

  [[1 0 2]
   [1 0 4]
   [3 1 1]]

  [[0 2 1]
   [0 4 0]
   [1 1 1]]]


 [[[1 3 0]
   [3 4 1]
   [2 2 2]]

  [[3 0 1]
   [4 1 0]
   [2 2 4]]

  [[0 1 4]
   [1 0 1]
   [2 4 4]]

  [[1 4 1]
   [0 1 2]
   [4 4 3]]

  [[4 1 1]
   [1 2 3]
   [4 3 0]]

  [[1 1 0]
   [2 3 1]
   [3 0 4]]

  [[1 0 4]
   [3 1 1]
   [0 4 2]]

  [[0 4 0]
   [1 1 1]
   [4 2 3]]]


 [[[3 4 1]
   [2 2 2]
   [4 2 1]]

  [[4 1 0]
   [2 2 4]
   [2 1 4]]

  [[1 0 1]
   [2 4 4]
   [1 4 1]]

  [[0 1 2]
   [4 4 3]
   [4 1 1]]

  [[1 2 3]
   [4 3 0]
   [1 1 2]]

  [[2 3 1]
   [3 0 4]
   [1 2 4]]

  [[3 1 1]
   [0 4 2]
   [2 4 0]]

  [[1 1 1]
   [4 2 3]
   [4 0 3]]]


 [[[2 2 2]
   [4 2 1]
   [4 2 3]]

  [[2 2 4]
   [2 1 4]
   [2 3 0]]

  [[2 4 4]
   [1 4 1]
   [3 0 2]]

  [[4 4 3]
   [4 1 1]
   [0 2 3]]

  [[4 3 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [78]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(z):
    return np.asarray(z + z.T - np.diag(z.diagonal())).view(Symetric)

s = symetric(np.random.randint(0,10,(5,5)))
s[2,3] = 42
print(s)

[[ 5  4  4  8 15]
 [ 4  6 14 10 15]
 [ 4 14  1 42 10]
 [ 8 10 42  6  4]
 [15 15 10  4  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [84]:
z = np.ones((16,16))
k = 4
s = np.add.reduceat(np.add.reduceat(z, np.arange(0, z.shape[0],k), axis=0),np.arange(0,z.shape[1],k), axis=1)
print(s)

[[ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [89]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5

print(z[np.argsort(z)[-n:]])
print(z[np.argpartition(-z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9995 9998 9999 9997]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [91]:
z = np.array([('hello', 2.5, 3), ('world', 3.6, 2)])
r = np.core.records.fromarrays(z.T, names='col1, col2, col3', formats='S8, f8, i8')
print(r)

[(b'hello',  2.5, 3) (b'world',  3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [98]:
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

8.88 s ± 8.58 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
812 ms ± 1.22 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
484 ms ± 1.87 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [100]:
a = np.random.uniform(0,1,10)
b = np.random.uniform(0,1,10)

np.einsum('i->', a)
np.einsum('i,i->i', a,b)
np.einsum('i,i', a,b)
np.einsum('i,j->ij',a,b)

array([[ 0.12572809,  0.30732273,  0.37354312,  0.08520952,  0.22045765,
         0.23122256,  0.43194313,  0.42783695,  0.01637649,  0.38763704],
       [ 0.13653232,  0.33373198,  0.4056429 ,  0.09253185,  0.2394023 ,
         0.25109227,  0.46906141,  0.46460238,  0.01778377,  0.42094795],
       [ 0.0710615 ,  0.17369876,  0.21112651,  0.04816041,  0.12460263,
         0.13068695,  0.24413418,  0.24181337,  0.00925599,  0.21909239],
       [ 0.12293252,  0.3004894 ,  0.36523738,  0.08331489,  0.21555577,
         0.22608132,  0.42233886,  0.41832398,  0.01601235,  0.37901791],
       [ 0.07556169,  0.18469878,  0.22449676,  0.05121032,  0.13249348,
         0.13896312,  0.25959475,  0.25712697,  0.00984215,  0.2329671 ],
       [ 0.1168564 ,  0.28563727,  0.34718498,  0.07919693,  0.20490161,
         0.21490692,  0.40146414,  0.39764771,  0.01522092,  0.3602844 ],
       [ 0.01737589,  0.04247265,  0.05162445,  0.01177614,  0.03046771,
         0.03195545,  0.05969545,  0.05912797

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)